version: 2

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    - run:
        name: Clone liboqs
        command: cd oqs_test && scripts/clone_liboqs.sh
    - run:
        name: Build liboqs
        command: cd oqs_test && scripts/build_liboqs.sh
    - run:
        name: Build OpenSSL
        command: cd oqs_test && scripts/build_openssl.sh
    - run:
        name: Run unit tests
        command: cd oqs_test && mkdir -p test-results && python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs_test/test-results

jobs:
  debian-buster-amd64:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:debian-buster-amd64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 102
  ubuntu-xenial-x86_64:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 102

workflows:
  version: 2
  build:
    jobs:
      - debian-buster-amd64
      - ubuntu-xenial-x86_64
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - OQS-OpenSSL_1_0_2-stable
    jobs:
      - debian-buster-amd64
      - ubuntu-xenial-x86_64
